apiVersion: v1
kind: Service
metadata:
  name: phonepay-app-service
spec:
  type: NodePort
  selector:
    app: phonepay-app-deployment # Label selector to match the deployment
  ports:
    - protocol: TCP
      port: 80          # Port exposed to external world
      targetPort: 5000  # Port inside the container
      
