name: Build and Push to AWS ECR

# This workflow runs on pushes to the main branch
on:
  push:
    branches: ["main"]

# Environment variables available to all jobs and steps
env:
  ECR_REPOSITORY: fintech-application-cicd # <-- 👈 CHANGE THIS to your ECR repository name
  AWS_REGION: us-east-1 # <-- 👈 CHANGE THIS to your AWS region

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # These permissions are required for OIDC authentication
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
